# Generated by Django 5.2.6 on 2025-09-27 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершена'), ('failed', 'Неудачна')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_products', models.IntegerField(default=0, verbose_name='Всего продуктов')),
                ('uploaded_products', models.IntegerField(default=0, verbose_name='Загружено продуктов')),
                ('failed_products', models.IntegerField(default=0, verbose_name='Неудачных загрузок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начата')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем')),
            ],
            options={
                'verbose_name': 'Массовая загрузка',
                'verbose_name_plural': 'Массовые загрузки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hood_id', models.CharField(max_length=20, unique=True, verbose_name='Hood ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('path', models.CharField(max_length=500, verbose_name='Путь')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.hoodcategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория Hood.de',
                'verbose_name_plural': 'Категории Hood.de',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('html_description', models.TextField(blank=True, verbose_name='HTML описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('price_start', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стартовая цена')),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Рекомендованная цена')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('condition', models.CharField(choices=[('new', 'Новый'), ('likeNew', 'Как новый'), ('veryGood', 'Очень хорошее'), ('acceptable', 'Удовлетворительное'), ('refurbished', 'Восстановленный'), ('defect', 'С дефектом'), ('usedGood', 'Б/у хорошее')], default='new', max_length=20, verbose_name='Состояние')),
                ('item_mode', models.CharField(choices=[('classic', 'Классический аукцион'), ('buyItNow', 'Купить сейчас'), ('shopProduct', 'Товар магазина')], default='shopProduct', max_length=20, verbose_name='Режим товара')),
                ('ean', models.CharField(blank=True, max_length=20, verbose_name='EAN')),
                ('mpn', models.CharField(blank=True, max_length=100, verbose_name='MPN')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Производитель')),
                ('item_number', models.CharField(blank=True, max_length=100, verbose_name='Номер товара')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Вес (кг)')),
                ('dimensions', models.CharField(blank=True, max_length=200, verbose_name='Размеры')),
                ('material', models.CharField(blank=True, max_length=200, verbose_name='Материал')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Цвет')),
                ('category_id', models.CharField(blank=True, max_length=20, verbose_name='ID категории')),
                ('images', models.JSONField(default=list, verbose_name='Изображения')),
                ('gallery_url', models.URLField(blank=True, verbose_name='URL галереи')),
                ('picture_url', models.URLField(blank=True, verbose_name='URL изображения')),
                ('custom_specifics', models.JSONField(default=dict, verbose_name='Дополнительные характеристики')),
                ('product_properties', models.JSONField(default=dict, verbose_name='Свойства продукта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_uploaded_to_hood', models.BooleanField(default=False, verbose_name='Загружен на Hood.de')),
                ('hood_item_id', models.CharField(blank=True, max_length=50, verbose_name='ID товара на Hood.de')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Загружен на Hood.de')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем')),
                ('hood_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.hoodcategory', verbose_name='Категория Hood.de')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('success', 'Успешно'), ('error', 'Ошибка'), ('duplicate', 'Дубликат')], default='pending', max_length=20, verbose_name='Статус')),
                ('hood_item_id', models.CharField(blank=True, max_length=50, verbose_name='ID товара на Hood.de')),
                ('response_data', models.JSONField(default=dict, verbose_name='Данные ответа')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Лог загрузки',
                'verbose_name_plural': 'Логи загрузки',
                'ordering': ['-created_at'],
            },
        ),
    ]
