# Generated by Django 5.2.6 on 2025-09-28 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkupload',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='bulkupload',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bulkupload',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gallery_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='bulkupload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='product',
            name='auto_renew',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет'), ('1', '1'), ('0', '0')], default='no', max_length=3, verbose_name='Автопродление'),
        ),
        migrations.AddField(
            model_name='product',
            name='category2_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Вторая категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='deficiency_description',
            field=models.TextField(blank=True, verbose_name='Описание дефектов'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_days_not_on_stock_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дни доставки (под заказ ОТ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_days_not_on_stock_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дни доставки (под заказ ДО)'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_days_on_stock_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дни доставки (в наличии ОТ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_days_on_stock_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дни доставки (в наличии ДО)'),
        ),
        migrations.AddField(
            model_name='product',
            name='duration_in_days',
            field=models.IntegerField(choices=[(3, '3 дня'), (5, '5 дней'), (7, '7 дней'), (10, '10 дней'), (14, '14 дней')], default=7, verbose_name='Продолжительность в днях'),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_efficiency_class',
            field=models.CharField(blank=True, choices=[('A+++', 'A+++'), ('A++', 'A++'), ('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=5, verbose_name='Класс энергоэффективности'),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_label_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на энергетическую этикетку'),
        ),
        migrations.AddField(
            model_name='product',
            name='feature_background_color',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет'), ('1', '1'), ('0', '0')], default='no', max_length=3, verbose_name='Цветной фон'),
        ),
        migrations.AddField(
            model_name='product',
            name='feature_bold_title',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет'), ('1', '1'), ('0', '0')], default='no', max_length=3, verbose_name='Жирный заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='feature_category',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет'), ('1', '1'), ('0', '0')], default='no', max_length=3, verbose_name='Выделение в категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='feature_gallery',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет'), ('1', '1'), ('0', '0')], default='yes', max_length=3, verbose_name='Галерея изображений'),
        ),
        migrations.AddField(
            model_name='product',
            name='feature_home_page',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет'), ('1', '1'), ('0', '0')], default='no', max_length=3, verbose_name='На главной странице'),
        ),
        migrations.AddField(
            model_name='product',
            name='feature_home_page_image',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет'), ('1', '1'), ('0', '0')], default='no', max_length=3, verbose_name='Изображение на главной'),
        ),
        migrations.AddField(
            model_name='product',
            name='feature_xxl_image',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет'), ('1', '1'), ('0', '0')], default='no', max_length=3, verbose_name='XXL изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='fsk',
            field=models.CharField(blank=True, choices=[('0', '0'), ('6', '6'), ('12', '12'), ('16', '16'), ('18', '18'), ('unknown', 'Неизвестно')], max_length=10, verbose_name='Возрастные ограничения'),
        ),
        migrations.AddField(
            model_name='product',
            name='if_is_sold_out',
            field=models.CharField(choices=[('endLess', 'Бесконечно'), ('hide', 'Скрыть')], default='hide', max_length=10, verbose_name='Поведение при отсутствии'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет'), ('1', '1'), ('0', '0')], default='yes', max_length=3, verbose_name='Статус одобрения'),
        ),
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_name_sub_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_number_unique_flag',
            field=models.BooleanField(default=True, verbose_name='Флаг уникальности номера товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_purchase',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальное количество покупки'),
        ),
        migrations.AddField(
            model_name='product',
            name='no_identifier_flag',
            field=models.CharField(choices=[('1', '1'), ('0', '0')], default='0', max_length=1, verbose_name='Флаг отсутствия идентификатора'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_size',
            field=models.CharField(blank=True, max_length=100, verbose_name='Размер упаковки'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_unit',
            field=models.CharField(blank=True, choices=[('g', 'Грамм'), ('kg', 'Килограмм'), ('ml', 'Миллилитр'), ('l', 'Литр'), ('m', 'Метр'), ('qm', 'Квадратный метр'), ('cbm', 'Кубический метр'), ('Stk', 'Штука')], max_length=10, verbose_name='Единица упаковки'),
        ),
        migrations.AddField(
            model_name='product',
            name='pay_options',
            field=models.CharField(default='wireTransfer,payPal,cashOnDelivery', max_length=500, verbose_name='Варианты оплаты'),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_cat_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID категории магазина'),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_cat_id2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Дополнительная категория магазина'),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_cat_id3',
            field=models.CharField(blank=True, max_length=20, verbose_name='Третья категория магазина'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_info_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на технический паспорт'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_options',
            field=models.JSONField(blank=True, default=dict, verbose_name='Варианты продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Закупочная цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_tax',
            field=models.IntegerField(default=19, verbose_name='Налог с продаж (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipmethods',
            field=models.CharField(default='DHLPacket_nat,DHLPacket_eu', max_length=500, verbose_name='Методы доставки'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_desc',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_on_start_page',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=1, verbose_name='Показ на главной странице'),
        ),
        migrations.AddField(
            model_name='product',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала (dd.mm.yyyy)'),
        ),
        migrations.AddField(
            model_name='product',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала (HH:MM)'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('g', 'Грамм'), ('kg', 'Килограмм'), ('ml', 'Миллилитр'), ('l', 'Литр'), ('m', 'Метр'), ('qm', 'Квадратный метр'), ('cbm', 'Кубический метр'), ('Stk', 'Штука')], default='Stk', max_length=10, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='product',
            name='usk',
            field=models.CharField(blank=True, choices=[('0', '0'), ('6', '6'), ('12', '12'), ('16', '16'), ('18', '18'), ('unknown', 'Неизвестно')], max_length=10, verbose_name='Возрастные ограничения USK'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_shortened_flag',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет'), ('1', '1'), ('0', '0')], default='no', max_length=3, verbose_name='Сокращенная гарантия'),
        ),
        migrations.AlterField(
            model_name='bulkupload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='bulkupload',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем'),
        ),
        migrations.AlterField(
            model_name='bulkupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='bulkupload',
            name='total_products',
            field=models.IntegerField(default=0, verbose_name='Всего товаров'),
        ),
        migrations.AlterField(
            model_name='bulkupload',
            name='uploaded_products',
            field=models.IntegerField(default=0, verbose_name='Загружено товаров'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'Новый'), ('likeNew', 'Как новый'), ('veryGood', 'Очень хорошее'), ('acceptable', 'Удовлетворительное'), ('refurbished', 'Восстановленный'), ('defect', 'С дефектом'), ('usedGood', 'Б/у хорошее')], default='new', max_length=20, verbose_name='Состояние товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем'),
        ),
        migrations.AlterField(
            model_name='product',
            name='custom_specifics',
            field=models.JSONField(blank=True, default=dict, verbose_name='Пользовательские характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, max_length=20, verbose_name='EAN код'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='Список изображений'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер товара клиента'),
        ),
        migrations.AlterField(
            model_name='product',
            name='list_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Рекомендованная цена (UVP)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default='JV Möbel', max_length=100, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mpn',
            field=models.CharField(blank=True, max_length=100, verbose_name='MPN (номер производителя)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_start',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стартовая цена аукциона'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_properties',
            field=models.JSONField(blank=True, default=dict, verbose_name='Свойства продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Вес в кг'),
        ),
        migrations.AlterField(
            model_name='uploadlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='uploadlog',
            name='response_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные ответа'),
        ),
        migrations.AlterField(
            model_name='uploadlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('success', 'Успешно'), ('error', 'Ошибка'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='uploadlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
