# Generated by Django 5.2.6 on 2025-09-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_extend_product_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hood_item_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID товара на Hood.de'),
        ),
        migrations.AlterField(
            model_name='uploadlog',
            name='hood_item_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID товара на Hood.de'),
        ),
    ]
