# Generated by Django 5.2.6 on 2025-09-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_fix_hood_item_id_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category2_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Вторая категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ID категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deficiency_description',
            field=models.TextField(blank=True, default='', verbose_name='Описание дефектов'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Размеры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='EAN код'),
        ),
        migrations.AlterField(
            model_name='product',
            name='energy_efficiency_class',
            field=models.CharField(blank=True, choices=[('A+++', 'A+++'), ('A++', 'A++'), ('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='', max_length=5, verbose_name='Класс энергоэффективности'),
        ),
        migrations.AlterField(
            model_name='product',
            name='energy_label_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на энергетическую этикетку'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fsk',
            field=models.CharField(blank=True, choices=[('0', '0'), ('6', '6'), ('12', '12'), ('16', '16'), ('18', '18'), ('unknown', 'Неизвестно')], default='', max_length=10, verbose_name='Возрастные ограничения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_name_sub_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Подзаголовок товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Номер товара клиента'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mpn',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='MPN (номер производителя)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging_size',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Размер упаковки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging_unit',
            field=models.CharField(blank=True, choices=[('g', 'Грамм'), ('kg', 'Килограмм'), ('ml', 'Миллилитр'), ('l', 'Литр'), ('m', 'Метр'), ('qm', 'Квадратный метр'), ('cbm', 'Кубический метр'), ('Stk', 'Штука')], default='', max_length=10, verbose_name='Единица упаковки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_cat_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ID категории магазина'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_cat_id2',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Дополнительная категория магазина'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_cat_id3',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Третья категория магазина'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_info_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на технический паспорт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_desc',
            field=models.TextField(blank=True, default='', verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='usk',
            field=models.CharField(blank=True, choices=[('0', '0'), ('6', '6'), ('12', '12'), ('16', '16'), ('18', '18'), ('unknown', 'Неизвестно')], default='', max_length=10, verbose_name='Возрастные ограничения USK'),
        ),
    ]
