# Generated by Django 5.2.6 on 2025-10-01 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_fix_field_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('total_rows', models.IntegerField(default=0, verbose_name='Всего строк')),
                ('success_count', models.IntegerField(default=0, verbose_name='Успешно импортировано')),
                ('error_count', models.IntegerField(default=0, verbose_name='Ошибок')),
                ('status', models.CharField(choices=[('pending', 'В процессе'), ('success', 'Успешно'), ('error', 'Ошибка'), ('partial', 'Частично успешно')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_details', models.TextField(blank=True, verbose_name='Детали ошибок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Лог импорта',
                'verbose_name_plural': 'Логи импорта',
                'ordering': ['-created_at'],
            },
        ),
    ]
