# Generated by Django 5.2.6 on 2025-10-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_importlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='feature_gallery',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет'), ('1', '1'), ('0', '0')], default='no', max_length=3, verbose_name='Галерея изображений'),
        ),
    ]
