# Generated by Django 5.2.6 on 2025-10-02 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_fix_feature_gallery_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(max_length=50, verbose_name='Тип синхронизации')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Начальная дата')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Конечная дата')),
                ('total_orders_found', models.IntegerField(default=0, verbose_name='Найдено заказов')),
                ('orders_created', models.IntegerField(default=0, verbose_name='Создано заказов')),
                ('orders_updated', models.IntegerField(default=0, verbose_name='Обновлено заказов')),
                ('orders_failed', models.IntegerField(default=0, verbose_name='Ошибок обработки')),
                ('status', models.CharField(choices=[('pending', 'В процессе'), ('success', 'Успешно'), ('error', 'Ошибка'), ('partial', 'Частично успешно')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_details', models.TextField(blank=True, verbose_name='Детали ошибок')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Данные ответа')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начато')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
            ],
            options={
                'verbose_name': 'Лог синхронизации заказов',
                'verbose_name_plural': 'Логи синхронизации заказов',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hood_order_id', models.CharField(max_length=50, unique=True, verbose_name='ID заказа Hood.de')),
                ('order_number', models.CharField(blank=True, max_length=100, verbose_name='Номер заказа')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('paid', 'Оплачен'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен'), ('returned', 'Возвращен'), ('refunded', 'Возврат средств')], default='new', max_length=20, verbose_name='Статус заказа')),
                ('buyer_username', models.CharField(max_length=100, verbose_name='Имя пользователя покупателя')),
                ('buyer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email покупателя')),
                ('buyer_name', models.CharField(blank=True, max_length=200, verbose_name='Имя покупателя')),
                ('shipping_name', models.CharField(blank=True, max_length=200, verbose_name='Имя получателя')),
                ('shipping_company', models.CharField(blank=True, max_length=200, verbose_name='Компания')),
                ('shipping_address1', models.CharField(blank=True, max_length=200, verbose_name='Адрес 1')),
                ('shipping_address2', models.CharField(blank=True, max_length=200, verbose_name='Адрес 2')),
                ('shipping_city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('shipping_state', models.CharField(blank=True, max_length=100, verbose_name='Регион')),
                ('shipping_postal_code', models.CharField(blank=True, max_length=20, verbose_name='Почтовый индекс')),
                ('shipping_country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('shipping_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Подытог')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма налога')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма')),
                ('payment_method', models.CharField(blank=True, choices=[('wireTransfer', 'Банковский перевод'), ('payPal', 'PayPal'), ('invoice', 'Счет'), ('cashOnDelivery', 'Наложенный платеж'), ('cash', 'Наличные'), ('sofort', 'Sofort'), ('amazon', 'Amazon Pay'), ('klarna', 'Klarna')], max_length=20, verbose_name='Способ оплаты')),
                ('payment_status', models.CharField(blank=True, max_length=50, verbose_name='Статус платежа')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('shipping_method', models.CharField(blank=True, max_length=100, verbose_name='Способ доставки')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Номер отслеживания')),
                ('shipped_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('delivered_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Внутренние заметки')),
                ('order_date', models.DateTimeField(verbose_name='Дата заказа')),
                ('last_status_change', models.DateTimeField(blank=True, null=True, verbose_name='Последнее изменение статуса')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-order_date'],
                'indexes': [models.Index(fields=['hood_order_id'], name='products_or_hood_or_709ea9_idx'), models.Index(fields=['status'], name='products_or_status_bd22a2_idx'), models.Index(fields=['order_date'], name='products_or_order_d_96d064_idx'), models.Index(fields=['buyer_username'], name='products_or_buyer_u_6c4e64_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hood_item_id', models.CharField(blank=True, max_length=50, verbose_name='ID товара Hood.de')),
                ('item_title', models.CharField(max_length=200, verbose_name='Название товара')),
                ('item_sku', models.CharField(blank=True, max_length=100, verbose_name='Артикул товара')),
                ('item_ean', models.CharField(blank=True, max_length=20, verbose_name='EAN товара')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('variant_details', models.JSONField(blank=True, default=dict, verbose_name='Детали варианта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказах',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Предыдущий статус')),
                ('new_status', models.CharField(max_length=20, verbose_name='Новый статус')),
                ('change_reason', models.TextField(blank=True, verbose_name='Причина изменения')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='products.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История статуса заказа',
                'verbose_name_plural': 'История статусов заказов',
                'ordering': ['-changed_at'],
            },
        ),
    ]
